db layer added
kashifkhan0771/HostService pull request #2
Opened 2021-01-12 06:47 UTC by kashifkhan0771

Added db layer for micro service.

2021-01-12 07:08 UTC, ahab94 commented on db/client.go
> +}
Add line ending

2021-01-12 07:10 UTC, kashifkhan0771 commented on db/client.go
> +}
okay

2021-01-12 07:49 UTC, ahab94 requested changes
Feedback

2021-01-13 09:56 UTC, ahab94 commented on Dockerfile.dev
> +ARG DEVELOPER
Add line ending

2021-01-13 09:57 UTC, ahab94 commented on Makefile.variables
> +    ${DEV_IMAGE}
Add linr ending

2021-01-13 09:57 UTC, kashifkhan0771 commented on Dockerfile.dev
> +ARG DEVELOPER
okay

2021-01-13 09:57 UTC, ahab94 commented on db/mongo/client.go
> +	"github.com/kashifkhan0771/HostService/config"
Imports are not organised

2021-01-13 09:57 UTC, ahab94 commented on db/mysql/client.go
> +	"github.com/spf13/viper"
Imports are not ordered

2021-01-13 09:58 UTC, ahab94 commented on db/mysql/client_test.go
> +	"reflect"
Imports are not ordered

2021-01-13 09:58 UTC, ahab94 commented on host_service.sql
> +);
Add line ending

2021-01-13 09:58 UTC, kashifkhan0771 commented
Okay i will try to resolve all of these ASAP.

2021-01-13 09:59 UTC, ahab94 commented on scripts/check.sh
>  golangci-lint run
Add line ending

2021-01-13 09:59 UTC, ahab94 commented on scripts/format.sh
>  gofmt -l -w .
Add line ending

2021-01-13 09:59 UTC, ahab94 commented on scripts/test.sh
> +go test ./...
Add line ending

2021-01-13 10:17 UTC, merged