Feature/service layer
kashifkhan0771/HostService pull request #3
Opened 2021-01-15 10:03 UTC by kashifkhan0771

Service Layer and API Handlers Added

2021-01-15 10:06 UTC, ahab94 commented on handlers/edit_host.go
> +	if err := d.rt.Service().UpdateHost(host); err != nil {
RetrieveHost should be called in UpdateHost

2021-01-15 10:06 UTC, kashifkhan0771 commented on handlers/edit_host.go
> +	if err := d.rt.Service().UpdateHost(host); err != nil {
okay i will update the code accordingly ASAP.

2021-01-15 10:20 UTC, ahab94 commented on runtime.go
> +svc *service.Service
File not formatted

2021-01-15 10:20 UTC, ahab94 commented on service/host.go
> +}
Add new line before return

2021-01-15 10:22 UTC, ahab94 requested changes
Make sure you run make test and there are 0 issues. The files mist be formatted

2021-01-15 10:26 UTC, kashifkhan0771 commented
okay I will make these changes ASAP.

2021-01-18 06:20 UTC, ahab94 commented on db/mongo/client.go
>  	"github.com/pkg/errors"
Imports are not organized

2021-01-18 06:20 UTC, ahab94 commented on db/mysql/client.go
>  	"github.com/kashifkhan0771/HostService/config"
imports are not organized.

2021-01-18 06:21 UTC, ahab94 commented on handlers/delete_host.go
> +	"github.com/go-openapi/runtime/middleware"
imports are not organized.

2021-01-18 06:21 UTC, ahab94 commented on handlers/edit_host.go
> +	"github.com/go-openapi/runtime/middleware"
imports are not organized.

2021-01-18 06:21 UTC, ahab94 commented on handlers/get_host.go
> +	"github.com/go-openapi/runtime/middleware"
imports are not organized

2021-01-18 06:21 UTC, ahab94 commented on handlers/interface.go
> +	"github.com/go-openapi/loads"
imports are not organized

2021-01-18 06:23 UTC, ahab94 requested changes
more feedback

2021-01-19 05:44 UTC, ahab94 commented on db/mongo/client.go
> +	_, err := collection.InsertOne(context.TODO(), host)
revert

2021-01-19 05:44 UTC, ahab94 commented on db/mongo/client.go
> +	err := collection.FindOne(context.TODO(), bson.M{"_id": id}).Decode(&host)
revert

2021-01-19 05:44 UTC, ahab94 commented on db/mongo/client.go
> -	if _, err := collection.DeleteOne(context.TODO(), bson.M{"_id": id}); err != nil {
Its more cleaner the other way.

2021-01-19 05:45 UTC, ahab94 commented on db/mongo/client.go
> +	_, err := collection.UpdateOne(context.TODO(), bson.M{"_id": host.ID}, bson.M{"$set": host})
revert

2021-01-19 05:45 UTC, ahab94 commented on db/mongo/client.go
> +	err := collection.FindOne(context.TODO(), bson.M{"_id": id}).Decode(&host)
Why we are not returning api error now?

2021-01-19 05:46 UTC, ahab94 commented on db/mysql/client.go
> +	err := c.db.Get(&stu, fmt.Sprintf(`SELECT * FROM %s WHERE id = '%s'`, hostTableName, id))
Not sure why you did this way... the other once makes it cleaner and consize.

2021-01-19 05:46 UTC, ahab94 commented on db/mysql/client.go
> +
Why this extra line?

2021-01-19 05:47 UTC, ahab94 commented on handlers/delete_host.go
> +		case apiErr.IsError(domainErr.NotFound):
In DELETE/PATCH/POST/PUT if a dependent resource is not found... we return BAD REQUEST instead of Not found.

In GET we return not found.

2021-01-19 09:43 UTC, ahab94 commented on handlers/add_host.go
> +		return operations.NewAddHostConflict()
Its always going to be a conflict?

2021-01-19 09:44 UTC, ahab94 commented on handlers/delete_host.go
> +		case apiErr.IsError(domainErr.BadRequest):
On not found we will respond BadRequest. Not on Bad request... there is no api error vetting returned with bad request.

2021-01-19 09:44 UTC, ahab94 commented on handlers/edit_host.go
> +		return operations.NewEditHostBadRequest()
Always a bad request?

2021-01-19 09:44 UTC, kashifkhan0771 commented on handlers/add_host.go
> +		return operations.NewAddHostConflict()
i checked by adding the host. It added successfully

2021-01-19 09:45 UTC, ahab94 requested changes
Need to fix

2021-01-19 11:48 UTC, ahab94 commented on handlers/add_host.go
> +	var e mongo.WriteException
Don't think you will ever got writr error in mongo. You will need to list Hosts in add Host service layer by name param... if len is non zero return conflict api error and then handle at api handler level like we are doing for others.

2021-01-20 08:57 UTC, ahab94 commented on db/mongo/client.go
> +	uri := fmt.Sprintf("mongodb://%s:27017", viper.GetString(config.DbHost))
Why we removed this?

2021-01-20 08:58 UTC, ahab94 commented on db/mongo/client.go
> +	err := collection.FindOne(context.TODO(), bson.M{"_id": id}).Decode(&host)
this comment isn't addressed. 
it should be 

```
	if err := collection.FindOne(context.TODO(), bson.M{"_id": id}).Decode(&host); err !=nil{
                if err == mongo.ErrNoDocuments {
			return nil, domainErr.NewAPIError(domainErr.NotFound, fmt.Sprintf("host: %s not found", id))
		}
 		return nil, err
        }
```

Always use this pattern where there is only error being used from the function.

2021-01-20 09:16 UTC, kashifkhan0771 commented on db/mongo/client.go
> +	uri := fmt.Sprintf("mongodb://%s:27017", viper.GetString(config.DbHost))
In configuration file the port is set to mysql default port that is 3306. So for mongo db i had set it manually like this, because the connection was not getting established while hitting the API, and mongo db was throwing back an error

2021-01-22 07:29 UTC, merged